version: '2'
services:
    steward-app:
        image: steward
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://steward-postgresql:5432/steward
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    steward-postgresql:
        extends:
            file: postgresql.yml
            service: steward-postgresql
